### ISSUE TITLE
jvthumb is not updating

### ISSUE THREAD

**Issue by obiwone2000** [javinizer/Javinizer#358]
## Expected Behavior
Sorted Actress name and pic would be saved to the list for future use

## Current Behavior
The Actress info is not saving. Believe this is due to R18 becomes unavailable

## Your Environment
* Module version used: 2.5.10
* Operating System and PowerShell version: Windows 10, powershell 7.3.3

**Comment by obiwone2000** [comment]
Raised in the discord chat, hope this is getting on to the list of issues to be fixed

**Comment by seeyabye** [comment]
Should be usable now. Check the latest version.

**Comment by obiwone2000** [comment]
It is starting to get new entries, but I don't believe the entries are correct however. Example below

"Wakuimito","","Wakuimito","和久井美兎","wakui_mito.jpg",
"Ashinahonoka","","Ashinahonoka","芦名ほのか","asina_honoka.jpg",
"Takahatachihana","","Takahatachihana","高畑ちはな","takahata_tihana.jpg",
"Hafu Yuria","Hafu","Yuria","葉風ゆりあ","hakaze_yuria.jpg",
"Kashiwagi Konatsu","Kashiwagi","Konatsu","柏木こなつ","kasiwagi_konatu.jpg",
"Kitayamayū","","Kitayamayū","北山憂","kitayama_yuu.jpg",
"Otsu Alice","Otsu","Alice","乙アリス","otu_arisu.jpg",
"Aratārina","","Aratārina","新ありな","arata_arina.jpg",
"Minase Akari","Minase","Akari","皆瀬あかり","minase_akari.jpg",
"Iorihinano","","Iorihinano","伊織ひなの","iori_hinano.jpg",
"Yuzuriha Karen","Yuzuriha","Karen","楪カレン","yuzuriha_karen.jpg",
"Mai Tsubasa","Mai","Tsubasa","つばさ舞","tubasa_mai.jpg",
"Unpai","","Unpai","うんぱい","unpai.jpg",
"Amamiya Hanan","Amamiya","Hanan","天宮花南","amamiya_kanan.jpg",
"Kamikirei","","Kamikirei","神木麗","kamiki_rei.jpg",

**Comment by seeyabye** [comment]
What version and scraper are you currently using?

**Comment by obiwone2000** [comment]
Sorry, How do I check? I only updated the GUI to 2.5.13Sent from my iPhoneOn 7 May 2023, at 06:10, seeyabye ***@***.***> wrote:﻿
What version and scraper are you currently using?

**Comment by seeyabye** [comment]
If you can share your settings, it would be better.

From the look for the jvThumbs.csv you shared, it looks fine except for names where the last name and first name are merged. This is highly dependent on the source you are scraping from. I will need to know which scraper you are using before I further debug it.

**Comment by obiwone2000** [comment]
Just let me know what you need. I will share any files. I will provide them as soon as possible as I am traveling these days.Sent from my iPhoneOn 7 May 2023, at 08:12, seeyabye ***@***.***> wrote:﻿
If you can share your settings, it would be better.
From the look for the jvThumbs.csv you shared, it looks fine except for names where the last name and first name are merged. This is highly dependent on the source you are scraping from. I will need to know which scraper you are using before I further debug it.

**Comment by obiwone2000** [comment]
Attached my settings file, is that what you need?


￼

**Comment by obiwone2000** [comment]
{
  "throttlelimit": 3,
  "location.input": "X:\\",
  "location.output": "X:\\",
  "location.thumbcsv": "",
  "location.genrecsv": "",
  "location.uncensorcsv": "",
  "location.historycsv": "",
  "location.tagcsv": "",
  "location.log": "",
  "scraper.movie.aventertainment": false,
  "scraper.movie.aventertainmentja": true,
  "scraper.movie.r18dev": true,
  "scraper.movie.dmm": false,
  "scraper.movie.dmmja": true,
  "scraper.movie.jav321ja": true,
  "scraper.movie.javbus": false,
  "scraper.movie.javbusja": true,
  "scraper.movie.javbuszh": false,
  "scraper.movie.javdb": false,
  "scraper.movie.javdbzh": false,
  "scraper.movie.javlibrary": false,
  "scraper.movie.javlibraryja": true,
  "scraper.movie.javlibraryzh": false,
  "scraper.movie.mgstageja": true,
  "scraper.movie.tokyohot": false,
  "scraper.movie.tokyohotja": true,
  "scraper.movie.tokyohotzh": false,
  "scraper.option.dmm.scrapeactress": true,
  "scraper.option.idpreference": "id",
  "scraper.option.addmaleactors": false,
  "match.minimumfilesize": 0,
  "match.includedfileextension": [
    ".asf",
    ".avi",
    ".flv",
    ".m4v",
    ".mkv",
    ".mp4",
    ".mov",
    ".rmvb",
    ".wmv"
  ],
  "match.excludedfilestring": [
    "^.*-trailer*",
    "^.*-5\\."
  ],
  "match.regex": false,
  "match.regex.string": "([a-zA-Z|tT28]+-\\d+[zZ]?[eE]?)(?:-pt)?(\\d{1,2})?",
  "match.regex.idmatch": 1,
  "match.regex.ptmatch": 2,
  "sort.movetofolder": true,
  "sort.renamefile": true,
  "sort.renamefolderinplace": false,
  "sort.maxtitlelength": 40,
  "sort.movesubtitles": false,
  "sort.create.nfo": true,
  "sort.create.nfoperfile": true,
  "sort.download.actressimg": true,
  "sort.download.thumbimg": true,
  "sort.download.posterimg": true,
  "sort.download.screenshotimg": true,
  "sort.download.trailervid": false,
  "sort.download.timeoutduration": 100000,
  "sort.format.groupactress": false,
  "sort.format.delimiter": ", ",
  "sort.format.file": "<ID>",
  "sort.format.folder": "<ACTORS> - <ID> - <TITLE> (<YEAR>)",
  "sort.format.outputfolder": "",
  "sort.format.posterimg": "folder",
  "sort.format.thumbimg": "fanart",
  "sort.format.trailervid": "<ID>-trailer",
  "sort.format.nfo": "<ID>",
  "sort.format.screenshotimg": "fanart",
  "sort.format.screenshotimg.padding": 1,
  "sort.format.screenshotfolder": "extrafanart",
  "sort.format.actressimgfolder": ".actors",
  "sort.metadata.nfo.addaliases": false,
  "sort.metadata.nfo.mediainfo": true,
  "sort.metadata.nfo.addgenericrole": true,
  "sort.metadata.nfo.altnamerole": false,
  "sort.metadata.nfo.translate": false,
  "sort.metadata.nfo.translate.module": "googletrans",
  "sort.metadata.nfo.translate.field": "description",
  "sort.metadata.nfo.translate.language": "en",
  "sort.metadata.nfo.translate.deeplapikey": "",
  "sort.metadata.nfo.translate.keeporiginaldescription": true,
  "sort.metadata.nfo.displayname": "[<ID>] <TITLE>",
  "sort.metadata.nfo.firstnameorder": false,
  "sort.metadata.nfo.actresslanguageja": true,
  "sort.metadata.nfo.unknownactress": true,
  "sort.metadata.nfo.originalpath": false,
  "sort.metadata.nfo.actressastag": false,
  "sort.metadata.nfo.preferactressalias": true,
  "sort.metadata.nfo.format.tag": "<SET>",
  "sort.metadata.nfo.format.tagline": "",
  "sort.metadata.nfo.format.credits": [],
  "sort.metadata.thumbcsv": true,
  "sort.metadata.thumbcsv.autoadd": true,
  "sort.metadata.thumbcsv.convertalias": true,
  "sort.metadata.genrecsv": true,
  "sort.metadata.genrecsv.autoadd": true,
  "sort.metadata.tagcsv": true,
  "sort.metadata.tagcsv.autoadd": true,
  "sort.metadata.genre.ignore": [
    "^Featured Actress",
    "^Hi-Def",
    ".*sale.*",
    ".*mosaic.*"
  ],
  "sort.metadata.requiredfield": [
    "id",
    "coverurl",
    "genre",
    "maker",
    "releaseDate",
    "title"
  ],
  "sort.metadata.priority.actress": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.alternatetitle": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.coverurl": [
    "DmmJa",
    "JavlibraryJa",
    "JavbusJa",
    "Jav321Ja",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.description": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.director": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.genre": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.id": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.contentid": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.label": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.maker": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.releasedate": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.rating": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.runtime": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.series": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.screenshoturl": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.title": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "sort.metadata.priority.trailerurl": [
    "DmmJa",
    "Jav321Ja",
    "JavbusJa",
    "JavlibraryJa",
    "MGStageJa",
    "TokyoHotJa",
    "AVEntertainmentJa"
  ],
  "emby.url": "http://192.168.0.1:8096",
  "emby.apikey": "",
  "javlibrary.baseurl": "http://www.javlibrary.com",
  "javlibrary.browser.useragent": "",
  "javlibrary.cookie.cf_chl_2": "",
  "javlibrary.cookie.cf_chl_prog": "",
  "javlibrary.cookie.cf_clearance": "",
  "javlibrary.cookie.session": "",
  "javlibrary.cookie.userid": "",
  "javdb.cookie.session": "",
  "proxy.enabled": false,
  "proxy.host": "",
  "proxy.username": "",
  "proxy.password": "",
  "web.favorites.genre": [],
  "web.favorites.tag": [],
  "web.sort.recurse": false,
  "web.sort.strict": false,
  "web.sort.interactive": true,
  "web.sort.update": false,
  "web.sort.force": false,
  "web.sort.preview": false,
  "web.sort.recursedepth": 10,
  "web.sort.confirm": false,
  "web.sort.manualsearch.aventertainment": false,
  "web.sort.manualsearch.aventertainmentja": true,
  "web.sort.manualsearch.dmm": false,
  "web.sort.manualsearch.dmmja": true,
  "web.sort.manualsearch.jav321ja": true,
  "web.sort.manualsearch.javbus": false,
  "web.sort.manualsearch.javbusja": true,
  "web.sort.manualsearch.javbuszh": false,
  "web.sort.manualsearch.javdb": false,
  "web.sort.manualsearch.javdbzh": false,
  "web.sort.manualsearch.javlibrary": false,
  "web.sort.manualsearch.javlibraryja": true,
  "web.sort.manualsearch.javlibraryzh": false,
  "web.sort.manualsearch.mgstageja": true,
  "web.sort.manualsearch.r18dev": true,
  "web.sort.manualsearch.tokyohot": true,
  "web.sort.manualsearch.tokyohotja": true,
  "web.sort.manualsearch.tokyohotzh": true,
  "web.theme": "dark",
  "admin.log": true,
  "admin.log.level": "",
  "admin.updates.check": true
}

**Comment by seeyabye** [comment]
It's not scraping from R18Dev at the moment.
You need to include R18Dev in your `sort.metadata.priority` section

Seems like getting a thumbnail from DmmJa doesn't work right now, will need to take a look at that. R18Dev should be working though.

```json
...
"sort.metadata.priority.actress": [
"R18Dev",
"DmmJa",
"Jav321Ja",
"JavbusJa",
"JavlibraryJa",
"MGStageJa",
"TokyoHotJa",
"AVEntertainmentJa"
],
...
```

**Comment by obiwone2000** [comment]
Added R18Dev and tried. Still the same.
Name error, missing thumbnail path

I have also updated to 2.5.15

**Comment by seeyabye** [comment]
Could you share what video code are you using it with?

Also, what do you get when you use the following in powershell?

```pwsh
Get-R18DevData -Url <url_link_to_one_of_r18dev_video_page>
```

**Comment by obiwone2000** [comment]
Stars-734  I see the path for thumbnail using powershell but name is still wrong. I am using GUI though previously.

Get-R18DevData -Url https://r18.dev/videos/vod/movies/detail/-/id=1stars734r/

Source        : r18dev
Url           : https://r18.dev/videos/vod/movies/detail/-/id=1stars734r/
ContentId     : 1stars734r
Id            : STARS734
Title         : A Subordinate With Too Much Style Is Turned Into A Meat
                Slave By Blackmailing Him. The Lingerie Training Of The
                Power Harassment Boss In The Company! Rei Kamiki
Description   :
ReleaseDate   : 2023-04-13
ReleaseYear   : 2023
Runtime       : 140
Director      : Zaku Arai
Maker         : SOD Create
Label         : SOD star
Series        :
Actress       : @{LastName=; FirstName=Kamikirei; JapaneseName=神木麗;
                ThumbUrl=https://pics.dmm.co.jp/mono/actjpgs/kamiki_rei.jpg}
Genre         : {Embarrassment, Shame, Office Lady, Big Tits…}
CoverUrl      : https://pics.dmm.co.jp/mono/movie/1stars734r/1stars734rpl.jp
                g
ScreenshotUrl :
TrailerUrl    : https://cc3001.dmm.co.jp/litevideo/freepv/1/1st/1stars734/1s
                tars734_mhb_w.mp4

**Comment by seeyabye** [comment]
The thumbnail path looks correct from the output. Are you doing a fresh sort? It should output the right thumbnail url to jvThumbs.csv

As for the name, it looks correct from r18.dev's data. In fact on r18, there was no information on which is the FirstName and which is the LastName. It's just Romaji=Kamikirei

**Comment by seeyabye** [comment]
Have you tried the latest version? 2.5.17?

The GUI just calls the CLI version of Javinizer for most of the operation, so the results should be the same

I ran with the mostly default settings, and I had no issue getting jvThumbs.csv to update with the correct thumbnail.

![image](https://github.com/javinizer/Javinizer/assets/36906720/74f2d884-fc3b-4541-8b05-5ef864858957)

Unless I am misunderstanding something, but at this point I am still confused what is the issue.

**Comment by obiwone2000** [comment]
After updating to 2.5.17 and deleting the existing entry in jvthumb. its getting the thumbs path.
I guess the name is r18 bug instead. In terms of manual amendment, even after updating in GUI for the name, it still won't store in jvthumb. I assume the save happened at point of sorting and not at the point of saving the video. Either way, thanks for sorting the thumb path out. Appreciate all your help on this.
