### ISSUE TITLE
[Question] Instructions on how to use the SetOwned functionality

### ISSUE THREAD

**Issue by nothing2obvi** [javinizer/Javinizer#364]
The [GitBook](https://docs.jvlflame.net/) link no longer works so I’m not sure if it could have answered this question.

How can I use the SetOwned functionality? I feel like I used this a few years ago but can't seem to do it again now. I tried to follow the instructions in #127 but can't seem to find one of the values needed (`cfduid`). I can find `useragent`, `__cf_bm`, `cf_clearance`, `PHPSESSID`, and `session`. I googled `cfduid` and Cloudflare's website says they have [deprecated this value](https://blog.cloudflare.com/deprecating-cfduid-cookie/).

## Your Environment
* Module version used: Docker version of Javinizer 2.5.10
* Docker version: 4.17.0
* Operating System and PowerShell version: Mac OS Monterey 12.6, unsure of PowerShell version via Docker

**Comment by nothing2obvi** [comment]
I tried installing PowerShell 7.3.4 natively on my Mac, used `Javinizer -OpenSettings` to find the path for the settings file, and edited that `jvSettings.json` to include `cf_clearance`, `javlibrary.cookie.session`, `userid`, and `useragent`. I could not find `cf_chl_2`, `cf_chl_prog`, or `javdb.cookie.session`. In PowerShell I ran the following command and got the subsequent result. It appears to run through content I already have set as owned on JavLibrary, then some content that indeed is not matched on JavLibrary, then errors out on something that is located on JavLibrary.

**Command:**
```
Javinizer -Path "/path/to/JAV" -Recurse -SetOwned
```

**Logs:**
```
Strict                                                                          
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
Strict
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
WARNING: [ID-HERE] [Get-JavlibraryUrl] not matched on JavLibrary
Line |
  67 |              Write-JVLog -Write:$script:JVLogWrite -LogPath $script:JV …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [CORRECT-ID-HERE] [Set-JavlibraryOwned] Error occurred when setting owned status
     | for [https://www.javlibrary.com/en/?v=CORRECT-LINK]: [CORRECT-ID-HERE]
     | [Set-JavlibraryOwned] Timed out while setting owned status for
     | [https://www.javlibrary.com/en/?v=CORRECT-LINK]
```

**Comment by seeyabye** [comment]
Probably some things have changed since then. Unless you get kicked in with Cloudflare asking to check if you're a bot, you probably can leave those fields empty.

However, I think the current `SetOwned` is broken, and you will probably need to wait for version 2.5.15. Otherwise, if you're comfortable cloning the current master repo, you can try to manually import it and give it a try.

The documentation has been restored and you can access it from [https://javinizer.gitbook.io/docs](https://javinizer.gitbook.io/docs).

**Comment by seeyabye** [comment]
Should be resolved from 2.5.15.

**Comment by nothing2obvi** [comment]
Should this work by now? I have installed 2.5.17 and I still get the same error as in my original post.
